apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
        - name: php
          image: {{ .Values.php.image }}:{{ .Values.php.tag }}
          ports:
            - containerPort: {{ .Values.php.port }}
        - name: nginx
          image: {{ .Values.nginx.image }}:{{ .Values.nginx.tag }}
          ports:
            - containerPort: {{ .Values.nginx.port }}
